version: '3.8'

services:
  backend:
    build: .
    environment:
      - SERVICE=backend
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
    
  frontend:
    build: .
    environment:
      - SERVICE=frontend
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
